name: code_connect_common
description: Common components and utilities for Code Connect applications.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.1
  json_annotation: ^4.8.1
  rust_core: ^0.3.6

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  test: ^1.24.0
